  CREATE TABLE imdb (
  imdbID CHAR(9) PRIMARY KEY NOT NULL,
  Title TEXT,
  Year CHAR(4),
  Director TEXT,
  Writer TEXT,
  Actors TEXT,
  Country TEXT,
  Language TEXT,
  Released TEXT,
  Location TEXT,
  Budget TEXT,
  Gross  TEXT,
  Production_Co TEXT,
  Runtime TEXT,
  "Cast" TEXT,
  Plot TEXT,
  Genre TEXT,
  Keywords TEXT,
  Awards TEXT,
  Metascore float,
  imdbRating float,
  imdbVotes int,
  Running_time TEXT,
  Certificate TEXT,
  Rated TEXT,
  Also_Known_As TEXT,
  Description TEXT,
  create_dt datetime,
  update_dt datetime
);
CREATE UNIQUE INDEX imdb_imdbid on imdb(imdbID);
